main: org.ctp.coldstorage.ColdStorage
version: 2.1.5
name: ColdStorage
api-version: 1.16
depend: [CrashAPI]
commands:
    csopen:
        description: Opens the cold storage
        permission: coldstorage.open
    csadmin:
        description: Edits cold storage information
        permission: coldstorage.admin
    csreload:
        description: Edits cold storage information
        permission: coldstorage.reload
    cschest:
        description: Add import/export chest
        permission: coldstorage.chest
    coldstorage:
        description: Main command for ColdStorage
    cshelp:
        description: Commands player can use
        permission: coldstorage.help
permissions:
    coldstorage.open:
        description: Allows player to open their cold storages
        default: true
    coldstorage.admin:
        description: Allows player to edit cold storage information
        default: op
    coldstorage.reload:
        description: Allows player to reload configuration files
        default: op
    coldstorage.remove_chests:
        description: Allows player to destroy other people's chests
        default: op
    coldstorage.chest:
        description: Allows player to add import/export chests
        default: true
    coldstorage.help:
        description: Allows player to view information on commands they can use
        default: true