main: org.ctp.coldstorage.ColdStorage
version: 2.0.4
name: ColdStorage
api-version: 1.13
commands:
    open:
        description: Opens the cold storage
        permission: coldstorage.open
    admin:
        description: Edits cold storage information
        permission: coldstorage.admin
    csreload:
        description: Edits cold storage information
        permission: coldstorage.reload
    chest:
        description: Add import/export chest
        permission: coldstorage.chest
permissions:
    coldstorage.open:
        description: Allows player to open their cold storages
        default: true
    coldstorage.admin:
        description: Allows player to edit cold storage information
        default: op
    coldstorage.reload:
        description: Allows player to reload configuration files
        default: op
    coldstorage.remove_chests:
        description: Allows player to destroy other people's chests
        default: op
    coldstorage.chest:
        description: Allows player to add import/export chests
        default: true