main: org.ctp.coldstorage.ColdStorage
version: 1.1.3
name: ColdStorage
api-version: 1.13
commands:
    csopen:
        description: Opens the cold storage
        permission: coldstorage.open
    csreload:
        description: Reload the cold storage configs
        permission: coldstorage.reload
    csadmin:
        description: Opens another player's cold storage as admin
        permission: coldstorage.admin
permissions:
    coldstorage.reload:
        description: Allows player to reload the configs
        default: op
    coldstorage.admin:
        description: Allows player to open other player's cold storages
        default: op
    coldstorage.free:
        description: Allows player to create cold storages for free
        default: false
    coldstorage.delete:
        description: Allows player to delete their own cold storages
        default: true
    coldstorage.open:
        description: Allows player to open their cold storages
        default: true
    coldstorage.admindelete:
        description: Allows player to delete other player's cold storages
        default: false